---
$id: http://schema.org.apievangelist.com/schema/objects/PropertyValueSpecification.json
schema: http://json-schema.org/draft-07/schema#
description: A Property value specification.
properties:
  defaultValue:
    description: The default value of the input.  For properties that expect a literal,
      the default is a literal value, for properties that expect an object, it s an
      ID reference to one of the current values.
    type: string
  minValue:
    description: The lower value of some characteristic or property.
    type: number
    format: float
  valuePattern:
    description: Specifies a regular expression for testing literal values according
      to the HTML spec.
    type: string
  stepValue:
    description: The stepValue attribute indicates the granularity that is expected
      (and required) of the value in a PropertyValueSpecification.
    type: number
    format: float
  valueMaxLength:
    description: Specifies the allowed range for number of characters in a literal
      value.
    type: number
    format: float
  readonlyValue:
    description: Whether or not a property is mutable.  Default is false. Specifying
      this for a property that also has a value makes it act similar to a  hidden  input
      in an HTML form.
    type: boolean
  valueMinLength:
    description: Specifies the minimum allowed range for number of characters in a
      literal value.
    type: number
    format: float
  maxValue:
    description: The upper value of some characteristic or property.
    type: number
    format: float
  valueName:
    description: Indicates the name of the PropertyValueSpecification to be used in
      URL templates and form encoding in a manner analogous to HTML s input@name.
    type: string
  multipleValues:
    description: Whether multiple values are allowed for the property.  Default is
      false.
    type: boolean
  valueRequired:
    description: Whether the property must be filled in to complete the action.  Default
      is false.
    type: boolean
...
