- swagger: "2.0"
  info:
    title: Engine Specification API
    description: Information about the engine of the vehicle. A vehicle can have multiple
      engines represented by multiple engine specification entities.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: engine.specification.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /engine-specification/:
      get:
        summary: Get Engine Specification
        description: Returns Engine Specification
        operationId: getEngineSpecification
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/EngineSpecification'
        tags:
        - Engine Specification
      post:
        summary: Add Engine Specification
        description: Add Engine Specification
        operationId: addEngineSpecification
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: fueltype
          in: formData
          description: The type of fuel suitable for the engine or engines of the vehicle.
            If the vehicle has only one engine, this property can be attached directly
            to the vehicle.
          required: false
          type: qualitativevalue or  text or  url
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: vehicleengine
          in: formData
          description: 'Information about the engine or engines of the vehicle. '
          required: false
          type: vehicle
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/EngineSpecification'
        tags:
        - Engine Specification
    /engine-specification/{id}/:
      get:
        summary: Get Engine Specification
        description: Returns a single Engine Specification
        operationId: getEngineSpecification
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/EngineSpecification'
        tags:
        - Engine Specification
      put:
        summary: Update Engine Specification
        description: Update a single Engine Specification
        operationId: updateEngineSpecificationItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: fueltype
          in: formData
          description: The type of fuel suitable for the engine or engines of the vehicle.
            If the vehicle has only one engine, this property can be attached directly
            to the vehicle.
          required: false
          type: qualitativevalue or  text or  url
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: vehicleengine
          in: formData
          description: 'Information about the engine or engines of the vehicle. '
          required: false
          type: vehicle
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/EngineSpecification'
        tags:
        - Engine Specification
      delete:
        summary: Engine Specification
        description: Deletes a single Engine Specification
        operationId: deleteEngineSpecification
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/EngineSpecification'
        tags:
        - Engine Specification
  definitions:
    EngineSpecification:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        description:
          description: A short description of the item.
          type: text
        fueltype:
          description: The type of fuel suitable for the engine or engines of the vehicle.
            If the vehicle has only one engine, this property can be attached directly
            to the vehicle.
          type: qualitativevalue or  text or  url
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        name:
          description: The name of the item.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        url:
          description: URL of the item.
          type: url
        vehicleengine:
          description: 'Information about the engine or engines of the vehicle. '
          type: vehicle