- swagger: "2.0"
  info:
    title: Medical Audience API
    description: Target audiences for medical web pages. Enumerated type.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: medical.audience.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /medical-audience/:
      get:
        summary: Get Medical Audience
        description: Returns Medical Audience
        operationId: getMedicalAudience
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Audience
      post:
        summary: Add Medical Audience
        description: Add Medical Audience
        operationId: addMedicalAudience
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: audiencetype
          in: formData
          description: The target group associated with a given audience (e.g. veterans,
            car owners, musicians, etc.).
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: geographicarea
          in: formData
          description: The geographic area associated with the audience.
          required: false
          type: administrativearea
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: healthcondition
          in: formData
          description: Expectations for health conditions of target audience.
          required: false
          type: medicalcondition
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: requiredgender
          in: formData
          description: Audiences defined by a person's gender.
          required: false
          type: text
        - name: requiredmaxage
          in: formData
          description: Audiences defined by a person's maximum age.
          required: false
          type: integer
        - name: requiredminage
          in: formData
          description: Audiences defined by a person's minimum age.
          required: false
          type: integer
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: suggestedgender
          in: formData
          description: The gender of the person or audience.
          required: false
          type: text
        - name: suggestedmaxage
          in: formData
          description: Maximal age recommended for viewing content.
          required: false
          type: number
        - name: suggestedminage
          in: formData
          description: Minimal age recommended for viewing content.
          required: false
          type: number
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: enumeration or  class or  property
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Audience
    /medical-audience/{id}/:
      get:
        summary: Get Medical Audience
        description: Returns a single Medical Audience
        operationId: getMedicalAudience
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Audience
      put:
        summary: Update Medical Audience
        description: Update a single Medical Audience
        operationId: updateMedicalAudienceItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: audiencetype
          in: formData
          description: The target group associated with a given audience (e.g. veterans,
            car owners, musicians, etc.).
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: geographicarea
          in: formData
          description: The geographic area associated with the audience.
          required: false
          type: administrativearea
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: healthcondition
          in: formData
          description: Expectations for health conditions of target audience.
          required: false
          type: medicalcondition
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: requiredgender
          in: formData
          description: Audiences defined by a person's gender.
          required: false
          type: text
        - name: requiredmaxage
          in: formData
          description: Audiences defined by a person's maximum age.
          required: false
          type: integer
        - name: requiredminage
          in: formData
          description: Audiences defined by a person's minimum age.
          required: false
          type: integer
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: suggestedgender
          in: formData
          description: The gender of the person or audience.
          required: false
          type: text
        - name: suggestedmaxage
          in: formData
          description: Maximal age recommended for viewing content.
          required: false
          type: number
        - name: suggestedminage
          in: formData
          description: Minimal age recommended for viewing content.
          required: false
          type: number
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: enumeration or  class or  property
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Audience
      delete:
        summary: Medical Audience
        description: Deletes a single Medical Audience
        operationId: deleteMedicalAudience
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Audience
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: audiencetype
          type: text
        description:
          description: The target group associated with a given audience (e.g. veterans,
            car owners, musicians, etc.).
          type: text
      - name:
          description: code
          type: medicalcode
        description:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: geographicarea
          type: administrativearea
        description:
          description: The geographic area associated with the audience.
          type: administrativearea
      - name:
          description: guideline
          type: medicalguideline
        description:
          description: A medical guideline related to this entity.
          type: medicalguideline
      - name:
          description: healthcondition
          type: medicalcondition
        description:
          description: Expectations for health conditions of target audience.
          type: medicalcondition
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: medicinesystem
          type: medicinesystem
        description:
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          type: medicinesystem
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: recognizingauthority
          type: organization
        description:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
      - name:
          description: relevantspecialty
          type: medicalspecialty
        description:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
      - name:
          description: requiredgender
          type: text
        description:
          description: Audiences defined by a person's gender.
          type: text
      - name:
          description: requiredmaxage
          type: integer
        description:
          description: Audiences defined by a person's maximum age.
          type: integer
      - name:
          description: requiredminage
          type: integer
        description:
          description: Audiences defined by a person's minimum age.
          type: integer
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: study
          type: medicalstudy
        description:
          description: A medical study or trial related to this entity.
          type: medicalstudy
      - name:
          description: suggestedgender
          type: text
        description:
          description: The gender of the person or audience.
          type: text
      - name:
          description: suggestedmaxage
          type: number
        description:
          description: Maximal age recommended for viewing content.
          type: number
      - name:
          description: suggestedminage
          type: number
        description:
          description: Minimal age recommended for viewing content.
          type: number
      - name:
          description: supersededby
          type: enumeration or  class or  property
        description:
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          type: enumeration or  class or  property
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url