- swagger: "2.0"
  info:
    title: Medical Entity API
    description: The most generic type of entity related to health and the practice
      of medicine.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: medical.entity.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /medical-entity/:
      get:
        summary: Get Medical Entity
        description: Returns Medical Entity
        operationId: getMedicalEntity
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalEntity'
        tags:
        - Medical Entity
      post:
        summary: Add Medical Entity
        description: Add Medical Entity
        operationId: addMedicalEntity
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: adverseoutcome
          in: formData
          description: 'A possible complication and/or side effect of this therapy.
            If it is known that an adverse outcome is serious (resulting in death, disability,
            or permanent damage; requiring hospitalization; or is otherwise life-threatening
            or requires immediate medical attention), tag it as a seriouseAdverseOutcome
            instead. '
          required: false
          type: medicaltherapy or medicaldevice
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: causeof
          in: formData
          description: 'The condition, complication, symptom, sign, etc. caused. '
          required: false
          type: medicalcause
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: estimatesriskof
          in: formData
          description: 'The condition, complication, or symptom whose risk is being
            estimated. '
          required: false
          type: medicalriskestimator
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: guidelinesubject
          in: formData
          description: 'The medical conditions, treatments, etc. that are the subject
            of the guideline. '
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: increasesriskof
          in: formData
          description: 'The condition, complication, etc. influenced by this factor. '
          required: false
          type: medicalriskfactor
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: seriousadverseoutcome
          in: formData
          description: 'A possible serious complication and/or serious side effect of
            this therapy. Serious adverse outcomes include those that are life-threatening;
            result in death, disability, or permanent damage; require hospitalization
            or prolong existing hospitalization; cause congenital anomalies or birth
            defects; or jeopardize the patient and may require medical or surgical intervention
            to prevent one of the outcomes in this definition. '
          required: false
          type: medicaltherapy or medicaldevice
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: studysubject
          in: formData
          description: 'A subject of the study, i.e. one of the medical conditions,
            therapies, devices, drugs, etc. investigated by the study. '
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalEntity'
        tags:
        - Medical Entity
    /medical-entity/{id}/:
      get:
        summary: Get Medical Entity
        description: Returns a single Medical Entity
        operationId: getMedicalEntity
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalEntity'
        tags:
        - Medical Entity
      put:
        summary: Update Medical Entity
        description: Update a single Medical Entity
        operationId: updateMedicalEntityItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: adverseoutcome
          in: formData
          description: 'A possible complication and/or side effect of this therapy.
            If it is known that an adverse outcome is serious (resulting in death, disability,
            or permanent damage; requiring hospitalization; or is otherwise life-threatening
            or requires immediate medical attention), tag it as a seriouseAdverseOutcome
            instead. '
          required: false
          type: medicaltherapy or medicaldevice
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: causeof
          in: formData
          description: 'The condition, complication, symptom, sign, etc. caused. '
          required: false
          type: medicalcause
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: estimatesriskof
          in: formData
          description: 'The condition, complication, or symptom whose risk is being
            estimated. '
          required: false
          type: medicalriskestimator
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: guidelinesubject
          in: formData
          description: 'The medical conditions, treatments, etc. that are the subject
            of the guideline. '
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: increasesriskof
          in: formData
          description: 'The condition, complication, etc. influenced by this factor. '
          required: false
          type: medicalriskfactor
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: seriousadverseoutcome
          in: formData
          description: 'A possible serious complication and/or serious side effect of
            this therapy. Serious adverse outcomes include those that are life-threatening;
            result in death, disability, or permanent damage; require hospitalization
            or prolong existing hospitalization; cause congenital anomalies or birth
            defects; or jeopardize the patient and may require medical or surgical intervention
            to prevent one of the outcomes in this definition. '
          required: false
          type: medicaltherapy or medicaldevice
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: studysubject
          in: formData
          description: 'A subject of the study, i.e. one of the medical conditions,
            therapies, devices, drugs, etc. investigated by the study. '
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalEntity'
        tags:
        - Medical Entity
      delete:
        summary: Medical Entity
        description: Deletes a single Medical Entity
        operationId: deleteMedicalEntity
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalEntity'
        tags:
        - Medical Entity
  definitions:
    MedicalEntity:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        adverseoutcome:
          description: 'A possible complication and/or side effect of this therapy.
            If it is known that an adverse outcome is serious (resulting in death, disability,
            or permanent damage; requiring hospitalization; or is otherwise life-threatening
            or requires immediate medical attention), tag it as a seriouseAdverseOutcome
            instead. '
          type: medicaltherapy or medicaldevice
        alternatename:
          description: An alias for the item.
          type: text
        causeof:
          description: 'The condition, complication, symptom, sign, etc. caused. '
          type: medicalcause
        code:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
        description:
          description: A short description of the item.
          type: text
        estimatesriskof:
          description: 'The condition, complication, or symptom whose risk is being
            estimated. '
          type: medicalriskestimator
        guideline:
          description: A medical guideline related to this entity.
          type: medicalguideline
        guidelinesubject:
          description: 'The medical conditions, treatments, etc. that are the subject
            of the guideline. '
          type: medicalguideline
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: imageobject or  url
        increasesriskof:
          description: 'The condition, complication, etc. influenced by this factor. '
          type: medicalriskfactor
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        medicinesystem:
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          type: medicinesystem
        name:
          description: The name of the item.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        recognizingauthority:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
        relevantspecialty:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        seriousadverseoutcome:
          description: 'A possible serious complication and/or serious side effect of
            this therapy. Serious adverse outcomes include those that are life-threatening;
            result in death, disability, or permanent damage; require hospitalization
            or prolong existing hospitalization; cause congenital anomalies or birth
            defects; or jeopardize the patient and may require medical or surgical intervention
            to prevent one of the outcomes in this definition. '
          type: medicaltherapy or medicaldevice
        study:
          description: A medical study or trial related to this entity.
          type: medicalstudy
        studysubject:
          description: 'A subject of the study, i.e. one of the medical conditions,
            therapies, devices, drugs, etc. investigated by the study. '
          type: medicalstudy
        url:
          description: URL of the item.
          type: url