- swagger: "2.0"
  info:
    title: Drug Prescription Status API
    description: Indicates whether this drug is available by prescription or over-the-counter.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: drug.prescription.status.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /drug-prescription-status/:
      get:
        summary: Get Drug Prescription Status
        description: Returns Drug Prescription Status
        operationId: getDrugPrescriptionStatus
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DrugPrescriptionStatus'
        tags:
        - Drug Prescription Status
      post:
        summary: Add Drug Prescription Status
        description: Add Drug Prescription Status
        operationId: addDrugPrescriptionStatus
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: prescriptionstatus
          in: formData
          description: 'Indicates whether this drug is available by prescription or
            over-the-counter. '
          required: false
          type: drug
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: enumeration or  class or  property
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DrugPrescriptionStatus'
        tags:
        - Drug Prescription Status
    /drug-prescription-status/{id}/:
      get:
        summary: Get Drug Prescription Status
        description: Returns a single Drug Prescription Status
        operationId: getDrugPrescriptionStatus
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DrugPrescriptionStatus'
        tags:
        - Drug Prescription Status
      put:
        summary: Update Drug Prescription Status
        description: Update a single Drug Prescription Status
        operationId: updateDrugPrescriptionStatusItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: prescriptionstatus
          in: formData
          description: 'Indicates whether this drug is available by prescription or
            over-the-counter. '
          required: false
          type: drug
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: enumeration or  class or  property
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DrugPrescriptionStatus'
        tags:
        - Drug Prescription Status
      delete:
        summary: Drug Prescription Status
        description: Deletes a single Drug Prescription Status
        operationId: deleteDrugPrescriptionStatus
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DrugPrescriptionStatus'
        tags:
        - Drug Prescription Status
  definitions:
    DrugPrescriptionStatus:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        code:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
        description:
          description: A short description of the item.
          type: text
        guideline:
          description: A medical guideline related to this entity.
          type: medicalguideline
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        medicinesystem:
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          type: medicinesystem
        name:
          description: The name of the item.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        prescriptionstatus:
          description: 'Indicates whether this drug is available by prescription or
            over-the-counter. '
          type: drug
        recognizingauthority:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
        relevantspecialty:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        study:
          description: A medical study or trial related to this entity.
          type: medicalstudy
        supersededby:
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          type: enumeration or  class or  property
        url:
          description: URL of the item.
          type: url