- "{\n\t\"swagger\": \"2.0\",\n\t\"info\": {\n\t\t\"title\": \"Boarding Policy Type
    API\",\n\t\t\"description\": \"A type of boarding policy used by an airline.\",\n\t\t\"termsOfService\":
    \"http://apievangelist.com/terms-of-service.html\",\n\t\t\"version\": \"v1\"\n\t},\n\t\"host\":
    \"boarding.policy.type.example.com\",\n\t\"basePath\": \"/\",\n\t\"schemes\": [\"http\"],\n\t\"produces\":
    [\"application/json\"],\n\t\"paths\": {\n\t\t\"/boarding-policy-type/\": {\n\t\t\t\"get\":
    {\n\t\t\t\t\"summary\": \"Get Boarding Policy Type\",\n\t\t\t\t\"description\":
    \"Returns Boarding Policy Type\",\n\t\t\t\t\"operationId\": \"getBoardingPolicyType\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"q\",\n\t\t\t\t\t\"in\": \"query\",\n\t\t\t\t\t\"description\":
    \"Keyword search for item\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"string\"\n\t\t\t\t}],\n\t\t\t\t\"responses\": {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\":
    \"A successful response.\",\n\t\t\t\t\t\t\"schema\": {\n\t\t\t\t\t\t\t\"type\":
    \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\": \"#/definitions/BoardingPolicyType\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Boarding Policy Type\"]\n\t\t\t},\n\t\t\t\"post\": {\n\t\t\t\t\"summary\": \"Add
    Boarding Policy Type\",\n\t\t\t\t\"description\": \"Add Boarding Policy Type\",\n\t\t\t\t\"operationId\":
    \"addBoardingPolicyType\",\n\t\t\t\t\"parameters\": [{\n\t\t\t\t\t\"name\": \"additionaltype\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"An additional type for the item, typically
    used for adding more specific types from external vocabularies in microdata syntax.
    This is a relationship between something and a class that the thing is in. In RDFa
    syntax, it is better to use the native RDFa syntax - the \\'typeof\\' attribute
    - for multiple types. Schema.org tools may have only weaker understanding of extra
    types, in particular those defined externally.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"alternatename\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"An alias for the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"boardingpolicy\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"The type of boarding policy used by the airline (e.g. zone-based or group-based).
    \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"airline or flight\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"description\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A
    short description of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"image\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"An image of the item. This can be a
    URL or a fully described ImageObject.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"mainentityofpage\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"Indicates a page (or other CreativeWork)
    for which this thing is the main entity being described.            See background
    notes for details.       Inverse property: mainEntity.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url or  creativework\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"name\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The name
    of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"potentialaction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a potential Action, which describes an idealized action in which this
    thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"sameas\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of a reference Web page that unambiguously
    indicates the item\\'s identity. E.g. the URL of the item\\'s Wikipedia page, Freebase
    page, or official website.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"supersededby\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"Relates a term (i.e. a property, class
    or enumeration) to one that supersedes it.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"class or  property or  enumeration\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"url\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"URL of the
    item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/BoardingPolicyType\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Boarding Policy Type\"]\n\t\t\t}\n\t\t},\n\t\t\"/boarding-policy-type/{id}/\":
    {\n\t\t\t\"get\": {\n\t\t\t\t\"summary\": \"Get Boarding Policy Type\",\n\t\t\t\t\"description\":
    \"Returns a single Boarding Policy Type\",\n\t\t\t\t\"operationId\": \"getBoardingPolicyType\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/BoardingPolicyType\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Boarding Policy Type\"]\n\t\t\t},\n\t\t\t\"put\": {\n\t\t\t\t\"summary\": \"Update
    Boarding Policy Type\",\n\t\t\t\t\"description\": \"Update a single Boarding Policy
    Type\",\n\t\t\t\t\"operationId\": \"updateBoardingPolicyTypeItem\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"additionaltype\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"alternatename\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An alias for the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"boardingpolicy\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The type of boarding policy used by
    the airline (e.g. zone-based or group-based). \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"airline or flight\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"description\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"A short description of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"image\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"An image
    of the item. This can be a URL or a fully described ImageObject.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"mainentityofpage\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"url or  creativework\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"name\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The name
    of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"potentialaction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a potential Action, which describes an idealized action in which this
    thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"sameas\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of a reference Web page that unambiguously
    indicates the item\\'s identity. E.g. the URL of the item\\'s Wikipedia page, Freebase
    page, or official website.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"supersededby\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"Relates a term (i.e. a property, class
    or enumeration) to one that supersedes it.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"class or  property or  enumeration\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"url\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"URL of the
    item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/BoardingPolicyType\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Boarding Policy Type\"]\n\t\t\t},\n\t\t\t\"delete\": {\n\t\t\t\t\"summary\":
    \"Boarding Policy Type\",\n\t\t\t\t\"description\": \"Deletes a single Boarding
    Policy Type\",\n\t\t\t\t\"operationId\": \"deleteBoardingPolicyType\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/BoardingPolicyType\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Boarding Policy Type\"]\n\t\t\t}\n\t\t}\n\t},\n\t\"definitions\": {\n\t\t\"BoardingPolicyType\":
    {\n\t\t\t\"properties\": {\n\t\t\t\t\"additionaltype\": {\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t\"alternatename\": {\n\t\t\t\t\t\"description\": \"An
    alias for the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"boardingpolicy\":
    {\n\t\t\t\t\t\"description\": \"The type of boarding policy used by the airline
    (e.g. zone-based or group-based). \",\n\t\t\t\t\t\"type\": \"airline or flight\"\n\t\t\t\t},\n\t\t\t\t\"description\":
    {\n\t\t\t\t\t\"description\": \"A short description of the item.\",\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t\"image\": {\n\t\t\t\t\t\"description\": \"An image
    of the item. This can be a URL or a fully described ImageObject.\",\n\t\t\t\t\t\"type\":
    \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t\"mainentityofpage\": {\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"type\": \"url or  creativework\"\n\t\t\t\t},\n\t\t\t\t\"name\":
    {\n\t\t\t\t\t\"description\": \"The name of the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"potentialaction\":
    {\n\t\t\t\t\t\"description\": \"Indicates a potential Action, which describes an
    idealized action in which this thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t\"sameas\": {\n\t\t\t\t\t\"description\": \"URL
    of a reference Web page that unambiguously indicates the item\\'s identity. E.g.
    the URL of the item\\'s Wikipedia page, Freebase page, or official website.\",\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t\"supersededby\": {\n\t\t\t\t\t\"description\": \"Relates
    a term (i.e. a property, class or enumeration) to one that supersedes it.\",\n\t\t\t\t\t\"type\":
    \"class or  property or  enumeration\"\n\t\t\t\t},\n\t\t\t\t\"url\": {\n\t\t\t\t\t\"description\":
    \"URL of the item.\",\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n}"