- swagger: "2.0"
  info:
    title: Taxi API
    description: A taxi.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: taxi.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /taxi/:
      get:
        summary: Get Taxi
        description: Returns Taxi
        operationId: getTaxi
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Taxi'
        tags:
        - Taxi
      post:
        summary: Add Taxi
        description: Add Taxi
        operationId: addTaxi
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: aggregaterating
          in: formData
          description: The overall rating, based on a collection of reviews or ratings,
            of the item.
          required: false
          type: aggregaterating
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: areaserved
          in: formData
          description: The geographic area where a service or offered item is provided.
            Supersedes serviceArea.
          required: false
          type: place or  geoshape or  administrativearea or  text
        - name: availablechannel
          in: formData
          description: A means of accessing the service (e.g. a phone bank, a web site,
            a location, etc.).
          required: false
          type: servicechannel
        - name: award
          in: formData
          description: An award won by or for this item. Supersedes awards.
          required: false
          type: text
        - name: category
          in: formData
          description: A category for the item. Greater signs or slashes can be used
            to informally indicate a category hierarchy.
          required: false
          type: physicalactivitycategory or  thing or  text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: hasoffercatalog
          in: formData
          description: Indicates an OfferCatalog listing for this Organization, Person,
            or Service.
          required: false
          type: offercatalog
        - name: hoursavailable
          in: formData
          description: The hours during which this service or contact is available.
          required: false
          type: openinghoursspecification
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: offers
          in: formData
          description: An offer to provide this item&#x2014;for example, an offer to
            sell a product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
          required: false
          type: offer
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: provider
          in: formData
          description: The service provider, service operator, or service performer;
            the goods producer. Another party (a seller) may offer those services or
            goods on behalf of the provider. A provider may also serve as the seller.
            Supersedes carrier.
          required: false
          type: organization or  person
        - name: providermobility
          in: formData
          description: Indicates the mobility of a provided service (e.g. \'static\',
            \'dynamic\').
          required: false
          type: text
        - name: review
          in: formData
          description: A review of the item. Supersedes reviews.
          required: false
          type: review
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: serviceoutput
          in: formData
          description: The tangible thing generated by the service, e.g. a passport,
            permit, etc. Supersedes produces.
          required: false
          type: thing
        - name: servicetype
          in: formData
          description: The type of service being offered, e.g. veterans\' benefits,
            emergency relief, etc.
          required: false
          type: text
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Taxi'
        tags:
        - Taxi
    /taxi/{id}/:
      get:
        summary: Get Taxi
        description: Returns a single Taxi
        operationId: getTaxi
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Taxi'
        tags:
        - Taxi
      put:
        summary: Update Taxi
        description: Update a single Taxi
        operationId: updateTaxiItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: aggregaterating
          in: formData
          description: The overall rating, based on a collection of reviews or ratings,
            of the item.
          required: false
          type: aggregaterating
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: areaserved
          in: formData
          description: The geographic area where a service or offered item is provided.
            Supersedes serviceArea.
          required: false
          type: place or  geoshape or  administrativearea or  text
        - name: availablechannel
          in: formData
          description: A means of accessing the service (e.g. a phone bank, a web site,
            a location, etc.).
          required: false
          type: servicechannel
        - name: award
          in: formData
          description: An award won by or for this item. Supersedes awards.
          required: false
          type: text
        - name: category
          in: formData
          description: A category for the item. Greater signs or slashes can be used
            to informally indicate a category hierarchy.
          required: false
          type: physicalactivitycategory or  thing or  text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: hasoffercatalog
          in: formData
          description: Indicates an OfferCatalog listing for this Organization, Person,
            or Service.
          required: false
          type: offercatalog
        - name: hoursavailable
          in: formData
          description: The hours during which this service or contact is available.
          required: false
          type: openinghoursspecification
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: offers
          in: formData
          description: An offer to provide this item&#x2014;for example, an offer to
            sell a product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
          required: false
          type: offer
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: provider
          in: formData
          description: The service provider, service operator, or service performer;
            the goods producer. Another party (a seller) may offer those services or
            goods on behalf of the provider. A provider may also serve as the seller.
            Supersedes carrier.
          required: false
          type: organization or  person
        - name: providermobility
          in: formData
          description: Indicates the mobility of a provided service (e.g. \'static\',
            \'dynamic\').
          required: false
          type: text
        - name: review
          in: formData
          description: A review of the item. Supersedes reviews.
          required: false
          type: review
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: serviceoutput
          in: formData
          description: The tangible thing generated by the service, e.g. a passport,
            permit, etc. Supersedes produces.
          required: false
          type: thing
        - name: servicetype
          in: formData
          description: The type of service being offered, e.g. veterans\' benefits,
            emergency relief, etc.
          required: false
          type: text
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Taxi'
        tags:
        - Taxi
      delete:
        summary: Taxi
        description: Deletes a single Taxi
        operationId: deleteTaxi
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Taxi'
        tags:
        - Taxi
  definitions:
    Taxi:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        aggregaterating:
          description: The overall rating, based on a collection of reviews or ratings,
            of the item.
          type: aggregaterating
        alternatename:
          description: An alias for the item.
          type: text
        areaserved:
          description: The geographic area where a service or offered item is provided.
            Supersedes serviceArea.
          type: place or  geoshape or  administrativearea or  text
        availablechannel:
          description: A means of accessing the service (e.g. a phone bank, a web site,
            a location, etc.).
          type: servicechannel
        award:
          description: An award won by or for this item. Supersedes awards.
          type: text
        category:
          description: A category for the item. Greater signs or slashes can be used
            to informally indicate a category hierarchy.
          type: physicalactivitycategory or  thing or  text
        description:
          description: A short description of the item.
          type: text
        hasoffercatalog:
          description: Indicates an OfferCatalog listing for this Organization, Person,
            or Service.
          type: offercatalog
        hoursavailable:
          description: The hours during which this service or contact is available.
          type: openinghoursspecification
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: url or  creativework
        name:
          description: The name of the item.
          type: text
        offers:
          description: An offer to provide this item&#x2014;for example, an offer to
            sell a product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
          type: offer
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        provider:
          description: The service provider, service operator, or service performer;
            the goods producer. Another party (a seller) may offer those services or
            goods on behalf of the provider. A provider may also serve as the seller.
            Supersedes carrier.
          type: organization or  person
        providermobility:
          description: Indicates the mobility of a provided service (e.g. \'static\',
            \'dynamic\').
          type: text
        review:
          description: A review of the item. Supersedes reviews.
          type: review
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        serviceoutput:
          description: The tangible thing generated by the service, e.g. a passport,
            permit, etc. Supersedes produces.
          type: thing
        servicetype:
          description: The type of service being offered, e.g. veterans\' benefits,
            emergency relief, etc.
          type: text
        url:
          description: URL of the item.
          type: url