- swagger: "2.0"
  info:
    title: Reported Dose Schedule API
    description: A patient-reported or observed dosing schedule for a drug or supplement.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: reported.dose.schedule.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /reported-dose-schedule/:
      get:
        summary: Get Reported Dose Schedule
        description: Returns Reported Dose Schedule
        operationId: getReportedDoseSchedule
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Reported Dose Schedule
      post:
        summary: Add Reported Dose Schedule
        description: Add Reported Dose Schedule
        operationId: addReportedDoseSchedule
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: doseunit
          in: formData
          description: The unit of the dose, e.g. 'mg'.
          required: false
          type: text
        - name: dosevalue
          in: formData
          description: The value of the dose, e.g. 500.
          required: false
          type: number
        - name: frequency
          in: formData
          description: How often the dose is taken, e.g. 'daily'.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: targetpopulation
          in: formData
          description: Characteristics of the population for which this is intended,
            or which typically uses it, e.g. 'adults'.
          required: false
          type: text
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Reported Dose Schedule
    /reported-dose-schedule/{id}/:
      get:
        summary: Get Reported Dose Schedule
        description: Returns a single Reported Dose Schedule
        operationId: getReportedDoseSchedule
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Reported Dose Schedule
      put:
        summary: Update Reported Dose Schedule
        description: Update a single Reported Dose Schedule
        operationId: updateReportedDoseScheduleItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: doseunit
          in: formData
          description: The unit of the dose, e.g. 'mg'.
          required: false
          type: text
        - name: dosevalue
          in: formData
          description: The value of the dose, e.g. 500.
          required: false
          type: number
        - name: frequency
          in: formData
          description: How often the dose is taken, e.g. 'daily'.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: targetpopulation
          in: formData
          description: Characteristics of the population for which this is intended,
            or which typically uses it, e.g. 'adults'.
          required: false
          type: text
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Reported Dose Schedule
      delete:
        summary: Reported Dose Schedule
        description: Deletes a single Reported Dose Schedule
        operationId: deleteReportedDoseSchedule
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Reported Dose Schedule
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: code
          type: medicalcode
        description:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: doseunit
          type: text
        description:
          description: The unit of the dose, e.g. 'mg'.
          type: text
      - name:
          description: dosevalue
          type: number
        description:
          description: The value of the dose, e.g. 500.
          type: number
      - name:
          description: frequency
          type: text
        description:
          description: How often the dose is taken, e.g. 'daily'.
          type: text
      - name:
          description: guideline
          type: medicalguideline
        description:
          description: A medical guideline related to this entity.
          type: medicalguideline
      - name:
          description: image
          type: imageobject or  url
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: imageobject or  url
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: medicinesystem
          type: medicinesystem
        description:
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          type: medicinesystem
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: recognizingauthority
          type: organization
        description:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
      - name:
          description: relevantspecialty
          type: medicalspecialty
        description:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: study
          type: medicalstudy
        description:
          description: A medical study or trial related to this entity.
          type: medicalstudy
      - name:
          description: targetpopulation
          type: text
        description:
          description: Characteristics of the population for which this is intended,
            or which typically uses it, e.g. 'adults'.
          type: text
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url