- swagger: "2.0"
  info:
    title: Bone API
    description: Rigid connective tissue that comprises up the skeletal structure of
      the human body.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: bone.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /bone/:
      get:
        summary: Get Bone
        description: Returns Bone
        operationId: getBone
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Bone
      post:
        summary: Add Bone
        description: Add Bone
        operationId: addBone
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: associatedpathophysiology
          in: formData
          description: If applicable, a description of the pathophysiology associated
            with the anatomical system, including potential abnormal changes in the
            mechanical, physical, and biochemical functions of the system.
          required: false
          type: text
        - name: bodylocation
          in: formData
          description: Location in the body of the anatomical structure.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: connectedto
          in: formData
          description: Other anatomical structures to which this structure is connected.
          required: false
          type: anatomicalstructure
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: diagram
          in: formData
          description: An image containing a diagram that illustrates the structure
            and/or its component substructures and/or connections with other structures.
          required: false
          type: imageobject
        - name: function
          in: formData
          description: Function of the anatomical structure.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: partofsystem
          in: formData
          description: The anatomical or organ system that this structure is part of.
          required: false
          type: anatomicalsystem
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relatedcondition
          in: formData
          description: A medical condition associated with this anatomy.
          required: false
          type: medicalcondition
        - name: relatedtherapy
          in: formData
          description: A medical therapy related to this anatomy.
          required: false
          type: medicaltherapy
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: substructure
          in: formData
          description: Component (sub-)structure(s) that comprise this anatomical structure.
          required: false
          type: anatomicalstructure
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Bone
    /bone/{id}/:
      get:
        summary: Get Bone
        description: Returns a single Bone
        operationId: getBone
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Bone
      put:
        summary: Update Bone
        description: Update a single Bone
        operationId: updateBoneItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: associatedpathophysiology
          in: formData
          description: If applicable, a description of the pathophysiology associated
            with the anatomical system, including potential abnormal changes in the
            mechanical, physical, and biochemical functions of the system.
          required: false
          type: text
        - name: bodylocation
          in: formData
          description: Location in the body of the anatomical structure.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: connectedto
          in: formData
          description: Other anatomical structures to which this structure is connected.
          required: false
          type: anatomicalstructure
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: diagram
          in: formData
          description: An image containing a diagram that illustrates the structure
            and/or its component substructures and/or connections with other structures.
          required: false
          type: imageobject
        - name: function
          in: formData
          description: Function of the anatomical structure.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: partofsystem
          in: formData
          description: The anatomical or organ system that this structure is part of.
          required: false
          type: anatomicalsystem
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relatedcondition
          in: formData
          description: A medical condition associated with this anatomy.
          required: false
          type: medicalcondition
        - name: relatedtherapy
          in: formData
          description: A medical therapy related to this anatomy.
          required: false
          type: medicaltherapy
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: substructure
          in: formData
          description: Component (sub-)structure(s) that comprise this anatomical structure.
          required: false
          type: anatomicalstructure
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Bone
      delete:
        summary: Bone
        description: Deletes a single Bone
        operationId: deleteBone
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Bone
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: associatedpathophysiology
          type: text
        description:
          description: If applicable, a description of the pathophysiology associated
            with the anatomical system, including potential abnormal changes in the
            mechanical, physical, and biochemical functions of the system.
          type: text
      - name:
          description: bodylocation
          type: text
        description:
          description: Location in the body of the anatomical structure.
          type: text
      - name:
          description: code
          type: medicalcode
        description:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
      - name:
          description: connectedto
          type: anatomicalstructure
        description:
          description: Other anatomical structures to which this structure is connected.
          type: anatomicalstructure
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: diagram
          type: imageobject
        description:
          description: An image containing a diagram that illustrates the structure
            and/or its component substructures and/or connections with other structures.
          type: imageobject
      - name:
          description: function
          type: text
        description:
          description: Function of the anatomical structure.
          type: text
      - name:
          description: guideline
          type: medicalguideline
        description:
          description: A medical guideline related to this entity.
          type: medicalguideline
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: medicinesystem
          type: medicinesystem
        description:
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          type: medicinesystem
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: partofsystem
          type: anatomicalsystem
        description:
          description: The anatomical or organ system that this structure is part of.
          type: anatomicalsystem
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: recognizingauthority
          type: organization
        description:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
      - name:
          description: relatedcondition
          type: medicalcondition
        description:
          description: A medical condition associated with this anatomy.
          type: medicalcondition
      - name:
          description: relatedtherapy
          type: medicaltherapy
        description:
          description: A medical therapy related to this anatomy.
          type: medicaltherapy
      - name:
          description: relevantspecialty
          type: medicalspecialty
        description:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: study
          type: medicalstudy
        description:
          description: A medical study or trial related to this entity.
          type: medicalstudy
      - name:
          description: substructure
          type: anatomicalstructure
        description:
          description: Component (sub-)structure(s) that comprise this anatomical structure.
          type: anatomicalstructure
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url