- swagger: "2.0"
  info:
    title: Diagnostic Procedure API
    description: A medical procedure intended primarily for diagnostic, as opposed to
      therapeutic, purposes.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: diagnostic.procedure.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /diagnostic-procedure/:
      get:
        summary: Get Diagnostic Procedure
        description: Returns Diagnostic Procedure
        operationId: getDiagnosticProcedure
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DiagnosticProcedure'
        tags:
        - Diagnostic Procedure
      post:
        summary: Add Diagnostic Procedure
        description: Add Diagnostic Procedure
        operationId: addDiagnosticProcedure
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: affectedby
          in: formData
          description: Drugs that affect the test\'s results.
          required: false
          type: drug
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: followup
          in: formData
          description: Typical or recommended followup care after the procedure is performed.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: howperformed
          in: formData
          description: How the procedure is performed.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: normalrange
          in: formData
          description: Range of acceptable values for a typical patient, when applicable.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: preparation
          in: formData
          description: Typical preparation that a patient must undergo before having
            the procedure performed.
          required: false
          type: text
        - name: proceduretype
          in: formData
          description: The type of procedure, for example Surgical, Noninvasive, or
            Percutaneous.
          required: false
          type: medicalproceduretype
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: signdetected
          in: formData
          description: A sign detected by the test.
          required: false
          type: medicalsign
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: usedtodiagnose
          in: formData
          description: A condition the test is used to diagnose.
          required: false
          type: medicalcondition
        - name: usesdevice
          in: formData
          description: Device used to perform the test.
          required: false
          type: medicaldevice
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DiagnosticProcedure'
        tags:
        - Diagnostic Procedure
    /diagnostic-procedure/{id}/:
      get:
        summary: Get Diagnostic Procedure
        description: Returns a single Diagnostic Procedure
        operationId: getDiagnosticProcedure
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DiagnosticProcedure'
        tags:
        - Diagnostic Procedure
      put:
        summary: Update Diagnostic Procedure
        description: Update a single Diagnostic Procedure
        operationId: updateDiagnosticProcedureItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: affectedby
          in: formData
          description: Drugs that affect the test\'s results.
          required: false
          type: drug
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: followup
          in: formData
          description: Typical or recommended followup care after the procedure is performed.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: howperformed
          in: formData
          description: How the procedure is performed.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: normalrange
          in: formData
          description: Range of acceptable values for a typical patient, when applicable.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: preparation
          in: formData
          description: Typical preparation that a patient must undergo before having
            the procedure performed.
          required: false
          type: text
        - name: proceduretype
          in: formData
          description: The type of procedure, for example Surgical, Noninvasive, or
            Percutaneous.
          required: false
          type: medicalproceduretype
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: signdetected
          in: formData
          description: A sign detected by the test.
          required: false
          type: medicalsign
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: usedtodiagnose
          in: formData
          description: A condition the test is used to diagnose.
          required: false
          type: medicalcondition
        - name: usesdevice
          in: formData
          description: Device used to perform the test.
          required: false
          type: medicaldevice
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DiagnosticProcedure'
        tags:
        - Diagnostic Procedure
      delete:
        summary: Diagnostic Procedure
        description: Deletes a single Diagnostic Procedure
        operationId: deleteDiagnosticProcedure
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/DiagnosticProcedure'
        tags:
        - Diagnostic Procedure
  definitions:
    DiagnosticProcedure:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        affectedby:
          description: Drugs that affect the test\'s results.
          type: drug
        alternatename:
          description: An alias for the item.
          type: text
        code:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
        description:
          description: A short description of the item.
          type: text
        followup:
          description: Typical or recommended followup care after the procedure is performed.
          type: text
        guideline:
          description: A medical guideline related to this entity.
          type: medicalguideline
        howperformed:
          description: How the procedure is performed.
          type: text
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        medicinesystem:
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          type: medicinesystem
        name:
          description: The name of the item.
          type: text
        normalrange:
          description: Range of acceptable values for a typical patient, when applicable.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        preparation:
          description: Typical preparation that a patient must undergo before having
            the procedure performed.
          type: text
        proceduretype:
          description: The type of procedure, for example Surgical, Noninvasive, or
            Percutaneous.
          type: medicalproceduretype
        recognizingauthority:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
        relevantspecialty:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        signdetected:
          description: A sign detected by the test.
          type: medicalsign
        study:
          description: A medical study or trial related to this entity.
          type: medicalstudy
        url:
          description: URL of the item.
          type: url
        usedtodiagnose:
          description: A condition the test is used to diagnose.
          type: medicalcondition
        usesdevice:
          description: Device used to perform the test.
          type: medicaldevice