- swagger: "2.0"
  info:
    title: Action Status Type API
    description: The status of an Action.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: action.status.type.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /action-status-type/:
      get:
        summary: Get Action Status Type
        description: Returns Action Status Type
        operationId: getActionStatusType
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/ActionStatusType'
        tags:
        - Action Status Type
      post:
        summary: Add Action Status Type
        description: Add Action Status Type
        operationId: addActionStatusType
        parameters:
        - name: actionstatus
          in: formData
          description: 'Indicates the current disposition of the Action. '
          required: false
          type: action
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: enumeration or  class or  property
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/ActionStatusType'
        tags:
        - Action Status Type
    /action-status-type/{id}/:
      get:
        summary: Get Action Status Type
        description: Returns a single Action Status Type
        operationId: getActionStatusType
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/ActionStatusType'
        tags:
        - Action Status Type
      put:
        summary: Update Action Status Type
        description: Update a single Action Status Type
        operationId: updateActionStatusTypeItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: actionstatus
          in: formData
          description: 'Indicates the current disposition of the Action. '
          required: false
          type: action
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: enumeration or  class or  property
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/ActionStatusType'
        tags:
        - Action Status Type
      delete:
        summary: Action Status Type
        description: Deletes a single Action Status Type
        operationId: deleteActionStatusType
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/ActionStatusType'
        tags:
        - Action Status Type
  definitions:
    ActionStatusType:
      properties:
      - name:
          description: actionstatus
          type: action
        description:
          description: 'Indicates the current disposition of the Action. '
          type: action
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: supersededby
          type: enumeration or  class or  property
        description:
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          type: enumeration or  class or  property
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url